KS-2-3 Train
CasTeTRU/KotlinSprintV2 pull request #10
Opened 2024-08-25 08:27 UTC by CasTeTRU

2024-08-27 15:15 UTC, ievetrovdev requested changes
А также обрати внимание на нейминг ветки и ПР

2024-08-27 15:15 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task3.kt
> +    println("$arrivalHour:$arrivalMinute")
А вот здесь как раз форматирование важно! Время хоть и выводится в формате [час:минуты], но не форматируется для двузначного представления минут и часов, попробуй посмотреть в сторону String.format

2024-08-27 15:15 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task3.kt
> +    val arrivalHour: Int = (departureHour * 60 + departureMinute + travelTime) / 60
тобы снизить риск ошибок, предлагаю еще вынести 60 в константу. Кроме того это [магическое число](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-08-27 15:15 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task3.kt
> +    println("$arrivalHour:$arrivalMinute")
По поводу разделения кода на блоки, отписал в комментах к прошлым задачам

2024-08-27 15:41 UTC, CasTeTRU commented
> А также обрати внимание на нейминг ветки и ПР

Вот здесь немного не понимаю:
Нейминг ветки: "_KS-2-3-Train_" - корректно? Номер урока + краткое описание, что решаем в задаче
Нейминг ПР "_KS-2-3-Train
Вместо магического числа добавлена константа времени
Сделано форматирование по абзацам
Вывод в консоль переделан под отображение представления минут и часов_" - Повторяю название ветки + расписываю что было изменено.
Или тут другая логика?

2024-08-28 04:16 UTC, ievetrovdev commented
> Нейминг ветки: "_KS-2-3-Train_" - корректно? Номер урока + краткое описание, что решаем в задаче
> Нейминг ПР "_KS-2-3-Train_

В целом это не так критично. Но на больших проектах, где задействовано много разработчиков, корректнее писать какое действие описывается в коде, чтобы человеку, первый раз увидевшему код, было легко ориентироваться. В данном случае, например так - KS-2-3-Train-arrival-calculation

2024-08-28 04:16 UTC, ievetrovdev approved these changes

2024-08-28 09:25 UTC, merged