KS-2-1 averageScore
CasTeTRU/KotlinSprintV2 pull request #8
Opened 2024-08-25 07:11 UTC by CasTeTRU

2024-08-26 16:31 UTC, CasTeTRU commented
KS-2-1 averageScore
In this case there is two digits after comma, should I be more specific and use output formatting in case of more than two digits after comma to match the requirements of the task?

2024-08-27 07:25 UTC, ievetrovdev commented
> KS-2-1 averageScore In this case there is two digits after comma, should I be more specific and use output formatting in case of more than two digits after comma to match the requirements of the task?

В целом это пока довольно базовые задачи. Продвинутыми способами решать не запрещается, но и простое решение, как у тебя в данной задаче корректно.

2024-08-27 07:40 UTC, ievetrovdev requested changes

2024-08-27 07:40 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task1.kt
> +    val averageScore: Double = (3.0 + 4.0 + 3.0 + 5.0) / 4
Значения в этом коде являются [магическими числами](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F). Не лучшая практика. Предлагаю добавить переменные)

2024-08-27 07:42 UTC, ievetrovdev requested changes
И давай вопросы писать на русском, мы все таки не иностранная компания)

2024-08-27 18:18 UTC, ievetrovdev requested changes

2024-08-27 18:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task1.kt
> +    val numberOfPupils = 4
Для красоты и читаемости лучше разбить код на блоки, разделяемые пустыми строками. Примерно так:
 - объявление переменных
 - вычисления
 - вывод результата

2024-08-28 13:10 UTC, ievetrovdev approved these changes
Теперь все корректно, аппрув!

И на будущее, предлагаю не резолвить треды здесь, все равно мне приходится их раскрывать чтобы войти в контекст)

2024-08-28 14:23 UTC, merged